{
 "title": "Inferyx",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Cache Hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "cache_hits_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cache Misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "cache_misses_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Worker Availability",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(worker_status) by (worker_id) != -1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inference Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(inference_latency_seconds_bucket[1m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(inference_latency_seconds_bucket[1m])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(inference_latency_seconds_bucket[1m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Current Retry Queue Size",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(retry_queue_size_gauge) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Jobs Expired",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(jobs_failed_after_retries_total[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Inference Queue Size",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(inference_queue_size_gauge) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Worker Queue Size",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(worker_queue_size_gauge) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "targets": [
    { "expr": "rate(jobs_processed_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Retries/sec",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "targets": [
    { "expr": "rate(retries_total[10s])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Retry Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "targets": [
    { "expr": "sum(retry_queue_size_gauge)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Failure/sec",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 28 },
   "targets": [
    { "expr": "rate(jobs_failure_total[5s])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Inference Requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "rate(inference_requests_total[5s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Jobs Skipped",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
   "targets": [
    { "expr": "rate(jobs_skipped_total[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Inference Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "sum(inference_queue_size_gauge)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batch Size Histogram",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(batch_size_hist_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 45 },
   "targets": [
    { "expr": "sum(worker_queue_size_gauge)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Batch Size/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "rate(batches_processed_total[5s])",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}